/**
 * Single entry point for every icon used in the app. Centralising the imports
 * means a rename in the icon library only needs fixing here.
 */
export {
  LayoutDashboard,
  LayoutGrid,
  Menu,
  Gauge,
  ScrollText,
  History,
  User,
  CircleUser,
  Plus,
  Minus,
  Check,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  Calendar,
  Trash2,
  CircleCheckBig as CheckCircle2,
  CircleX as XCircle,
  Info,
  TriangleAlert as AlertTriangle,
  Camera,
  Images,
  ZoomIn,
  ZoomOut,
  LogOut,
  Globe,
  Trophy,
  Sword,
  Flame,
  Star,
  Target,
  Sparkles,
  Gift,
  CircleArrowUp as ArrowUpCircle,
  Dumbbell,
  Wind,
  Brain,
  Heart,
  Eye,
  Zap,
  BookOpen,
  TrendingUp,
  Briefcase,
  Users,
  Gamepad2,
  type LucideIcon,
} from 'lucide-react-native'
